# This file was generated by GoReleaser. DO NOT EDIT.
cask "castle" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "castle", "clogs"], chdir: ".", must_succeed: false
    end
  end

  version "0.1.6"

  on_macos do
    on_arm do
      sha256 "34c4184a428181f6713c5446f45a4d16f50e4528775a5ce69d31e1723d74b6ea"
      url "https://github.com/evicoach/castle-releases/releases/download/v#{version}/castle_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "005114955176f41a3d7dd44ccc4cdaa7899f6ef1ba1ffe37665ae88696f67735"
      url "https://github.com/evicoach/castle-releases/releases/download/v#{version}/castle_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a5718fc7429060864e7491fe4fae06446f85784f537a616da3ac5c9775a558fb"
      url "https://github.com/evicoach/castle-releases/releases/download/v#{version}/castle_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "793f82037c92486e4adaf51baf57614c6951a7e403319e26c6996e708a2d071e"
      url "https://github.com/evicoach/castle-releases/releases/download/v#{version}/castle_#{version}_linux_amd64.tar.gz"
    end
  end

  name "castle"
  desc "Read the logs of services in secured environments from your own terminal"
  homepage "https://github.com/evicoach/castle-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "castle"
  binary "clogs"

  # No zap stanza required
end
