# This file was generated by GoReleaser. DO NOT EDIT.
cask "castle" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "e34072eef03e1f27843c4ed77e2e44f3f745c7f14f5c2f4b98b50d9a4123fe1a"
      url "https://github.com/evicoach/castle/releases/download/v#{version}/castle_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d1ee84dcb02c58043846c74e414ba534bb987704b833f300bc45f9a64b5c9a1d"
      url "https://github.com/evicoach/castle/releases/download/v#{version}/castle_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d544b16fe84b9c9354d74e63e1fdf6de63cc789f42268d9c407d9fbc5e5ea157"
      url "https://github.com/evicoach/castle/releases/download/v#{version}/castle_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f3976e55dfd72c846e9efcfb1e83a4e329d8af25c90fc0ec1bf19735e3d4c251"
      url "https://github.com/evicoach/castle/releases/download/v#{version}/castle_#{version}_linux_amd64.tar.gz"
    end
  end

  name "castle"
  desc "View and follow private AKS app logs through Azure Bastion"
  homepage "https://github.com/evicoach/castle"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "castle"
  binary "clogs"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/castle", "#{staged_path}/clogs"]
    end
  end

  # No zap stanza required
end
