# This file was generated by GoReleaser. DO NOT EDIT.
cask "castle" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "ce9a8f89e30f6ca5a34e5bc25e6fc6387e86394d2b20646b41678fac9a06aa75"
      url "https://github.com/evicoach/castle-releases/releases/download/v#{version}/castle_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6d485d8bc0293afecff3769d84f0c1b43d2480166dd84636e832d44485e0fd92"
      url "https://github.com/evicoach/castle-releases/releases/download/v#{version}/castle_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7c6250b7a299df57507fce66a19b55f17deb2f77ca53007fab74322ef73d4fef"
      url "https://github.com/evicoach/castle-releases/releases/download/v#{version}/castle_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2f3041877026f3d110b90bbf53a69b93dffc943535f69d638377aceca2d8cbcb"
      url "https://github.com/evicoach/castle-releases/releases/download/v#{version}/castle_#{version}_linux_amd64.tar.gz"
    end
  end

  name "castle"
  desc "Read the logs of services in secured private AKS environments from your terminal, through Azure Bastion"
  homepage "https://github.com/evicoach/castle-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "castle"
  binary "clogs"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/castle", "#{staged_path}/clogs"]
    end
  end

  # No zap stanza required
end
